hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "cf4ee864c556688f02f60429e4a259ddbeaa9cb8bba12876527874b5b9b76941"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "a882a408eebbda134df2d12b1b30e92a1c680d0dbd640bd05ec9ef8959720f73"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "bc7cfadfe7121fdbd356c7992705ea6f484de518d3fd473eb8c59ea93e79a04d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "ff07701398fd9f25c3a05a70155539887a2dbe065a956f55a157d40469698226"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "2bcd25f08afd77c9ec94392eef5762450a8b7d591356f93d04c19e89b5e56cba"

[[files]]
file = "mods/adorn.pw.toml"
hash = "a76d2ffabe522b72432aa3607fd7f133e2822d57ecfd53fe33287ecaa50c80ed"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "5041d4be9d64017c7891f46878b7fa0d528c277e45c1d5e6be74b22abead7028"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/atlas-core.pw.toml"
hash = "680ac6e11733cdb9d81df56aa79f563af2d3716ff00f69aa0ee2c288634fafc3"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b21ef031c6ad139361352529cb63f4799ffa91008895e1c7a9a5102ea007ae2d"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "3e0109bdcb98c740367fd5a2f455bea1d7663389266e3c34a237c5997a8c86b8"
metafile = true

[[files]]
file = "mods/better-cave-worlds.pw.toml"
hash = "93007bef22683650a31d0e802ef55d23ba3a78d87061871c8aed2a1baf985ae0"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "128d9dfd2156ffa54cea7621d3c3c2ac42d9865b3363996c08c70c5a52af98d0"
metafile = true

[[files]]
file = "mods/better-nether-map.pw.toml"
hash = "823d504f7256c8223cd30f2617753a8e5b6dc67dd223897fd16273421ef57960"
metafile = true

[[files]]
file = "mods/celestria.pw.toml"
hash = "ad7a1185a326fcad780c9a6fd5d489efda6c8b4f3582f4a8b2c377b384241210"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
hash = "89ff47b56152929c67e8cf972f18aac7f9ff8bd01970362521d09aba1da6027c"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/clifftree.pw.toml"
hash = "c7ceaae4e41a455b1adc72a1d1c327a02ce4d608b9c974fae2b80198ec8b19c6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/combatify.pw.toml"
hash = "e182cf3a5969b80bef83204ce1ee4adb76125434770cc86aa3675d326e8dedda"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "157e9ed75307c70b4c768fa15f3975b21ac5a70fc3580cd455e0aa8e23ff5d55"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "4f97764f3cb4c74f84afbe32cf8a1d2cefecda129c0f1441906562dcb8f2b8cb"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "578b663599a5687c8b96a7ed89af21eef3499f7daa20611d271701aa06ad6fe7"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "a07f5a28192fcedba35c2db7472b322b381827db29372393e9429ef13c056020"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "1350769c8b58f5e79ace1d873276da0043f619d8e71a3c7e18289794deb7fa2f"
metafile = true

[[files]]
file = "mods/defaulted.pw.toml"
hash = "1b54bcbdb22819281ae347adffde8313536b11fc7cc4a04038a4d8f65a3dbf48"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "71314f7a5609378c77f372c31d2c501a330cc901c6e4f6e060d7f3095d362086"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "d1f561a89e7a4c5d98b6cbb25088ea2ad56ca1cff60118f2076912f49f8cfed3"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "a4b817f8c3de5af3a6ecb2b72caa2daa3042c1e65cc8eb3c794a0b3ec3bbf847"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "a0b3f914a386d4236744bc749156bb7eca1014179a50e340af1ea4741198782f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9ee84bdf71ae7963fabc99e8bb44acb72334d281b02ddac913e25daf7b81c143"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "967a780be97bec40b8bca4945a053ee4fbd05d58e218c4fb803959ac0d0c7f08"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "8d6cb7e5cd8619b40c77903bc0be7178caa88cef4521559e6dec38d21471bbef"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "8945ea290647fec8b91c24bd81821ee1d73d84a968d23260dbee24ceb951db4d"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "69c5ae686703cc74e092591cd5a1939bd5cc2e8522f928c77a77ab803be5e77e"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4387abb74dcfc93f9381c109fe76e7161ca7a91a1a642db4781b47f650c4ddab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "17d991a9d3adc2f923bccf4bde22e648a6964c4934a2eee2f822e67345dc96fe"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
hash = "5f6ac813d736ea01425bf7c01612df6017e6a9ab465b39a341630ef1f6e05834"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "c73fc3680d04bd42fafb0ac3e5e2dfc9e50cff44453ecf91b1bebca6da5107eb"
metafile = true

[[files]]
file = "mods/hearths.pw.toml"
hash = "55f92a03df046f1ee4da2100025726e166576d47378932b685c56b9ff3da2a37"
metafile = true

[[files]]
file = "mods/ibo.pw.toml"
hash = "bea1c958d6af5041586adbd78d2f8bd1d081cc52bd4f74898edf7eccf5f850d5"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "ef1faa467f5dfd37c40871575934dab645f15a70568e8268a9e477234bdd1c58"
metafile = true

[[files]]
file = "mods/infinite-music.pw.toml"
hash = "6e7613d3b9726eaae758e8927e56c5be6bd53f09e8a370b20bc8df3dffab47a2"
metafile = true

[[files]]
file = "mods/inmis.pw.toml"
hash = "830096662326cf3a4c2b9565caed56f8c38f2a0fde20acfcd2615252a4b717fb"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d503a6ed4c0571f9ff04a67900e5f8307f1161a47767363bd343ee24817e6460"
metafile = true

[[files]]
file = "mods/legacy-mipmaps.pw.toml"
hash = "7cfa0c76fd2c82c12a6bb1238ecdec2576cfb448d5907821f2721702dea3889b"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "cd55593e129301fa89dc8751ce917157f256a6bf0f5056ab9c37875acc6fc768"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "dce9caabe87f4b80fd7566d0b773fd69ef122866eaa5bd51ba1b077ba163d276"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "e903d9958d442f8cbd2dd05806a85e59a7e8a7d499a0b016853b2fe90cd98615"
metafile = true

[[files]]
file = "mods/map-tooltip.pw.toml"
hash = "68167641fe33832f6bc3eac33825ddc85f40175d9ab2941406e251a9a2534104"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "0f9a9042aaea1f95a68c87325715308564ad6b173437dbcc3f7ac1c63d71b87d"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d2eef785df399c7b45f20ecc3d07e1749b4bff2b2f87dc1c47d3a339996569c2"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0aa27cfe48f3b4a1a485e6fddeb5d806301204130ac51a1352abc10cb05ca1aa"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "93c5b81a82fffca423eaae73c4ebd729b8d644aad0e35eda39c287f9778fc9a3"
metafile = true

[[files]]
file = "mods/netherite-extras.pw.toml"
hash = "c04f135ed867bf45dffffe438290c0f1839f484a7fdd8ee3931743473f352aef"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "537bdd1937193d94cf47f2232e2b38357415e5af8c950d97661b3ae881adbb4e"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "dcc936d7bd32a86ce63fa3bf013864a4e2ed979cb126a915153ac70ce5e5671f"
metafile = true

[[files]]
file = "mods/nostalgic-tweaks.pw.toml"
hash = "ee92e804c6ffd6509e621421b9906efa0f654885053b1ea00c7e4a4eb55dae17"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "a6e3ca19c98f18fcf6e8a89587c0fb15df4a2147db9ae1f18d3d2b178fce10ac"
metafile = true

[[files]]
file = "mods/notebook.pw.toml"
hash = "c56372d7a080853347b11805898bb2c7e1954887095ddc34242c116c587608ec"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "3ecb49498a9bfd8fb1f980236dbca36d42d5b458f539770b4b4124ffad9d76b5"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "e738806b1099f2b4b950ec57816582f3b7afd7a0074a250e3f120aa78350bc7e"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "58e380b4d66907130eaa480252def925457d1033100571c946aaf9179a1e7bde"
metafile = true

[[files]]
file = "mods/qdaa.pw.toml"
hash = "72849c84af6ec19ce9138e65fc855e929fd53a1293234a466acb76cffe205dbf"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/remapped.pw.toml"
hash = "c6d065400201339ef97a2925595170b034d71f4acbf185591b48ca5d1511ebff"
metafile = true

[[files]]
file = "mods/resolution-control-plus-plus.pw.toml"
hash = "49b4b01eb3aae1cd5c78da42945be2635d4adfe525404fdc046c8bf73d9f8b34"
metafile = true

[[files]]
file = "mods/satin-free-wakes.pw.toml"
hash = "da82584dc5c26adafb4df9b69fa2ed710ead914ce8384058665fcfa85950f5fa"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "a0229ecd63d478b8d019318a58317855c7e862cce95e78a60e21c01317cc329e"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "461adc31ce2b89cafc5ad2e846b482c68529231ac1d907e39ec62458b22e6b3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "0a6179657082b15117e18fbc80fd60538dc91024a63006e843cb5dbf1991bcbe"
metafile = true

[[files]]
file = "mods/sparsestructures.pw.toml"
hash = "c93c75286371a28af424057e77e4547b1bddd53b8d32e10c94b0bc158c5d91ed"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "784d31c38a90243c105fcbb5c7ccaae37c920eb91a4637b1f2dfb268ae1af4ee"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "e35593590fe988653baebae4638f6c93b5d822351274955cc1288b34fe5429fe"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "e77fe4473df0685a27bdc27f9a50c0dced4d298a2765301c2b1f0b11e078a887"
metafile = true

[[files]]
file = "mods/true-ending.pw.toml"
hash = "053774568056e43aef8b9e8cb2e626c84b97546c56a453346cc9077882e3c409"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "a60a3daa425e1d278d5a51abc60d3818979278970559ee1d392757c0b3e4f50b"
metafile = true

[[files]]
file = "mods/worldgen-patches.pw.toml"
hash = "a39b36424f533c3782535b2e47fde1fb3f26eb60eb11f2fef411910d0cec0e62"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9e505dd9481f099ebf08915d1d416cbf4f114fb72416e5d2a8cf2c696a409ae0"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "052b70117c2e9a3a697a36f449b220be7bfba215f3a2e43b5ce7faff9e88b2e6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "1bb9b2e75c6934b1f18648e9b37e20abcf6a4a2547c7cdb0abe88407267e0c10"
metafile = true

[[files]]
file = "resourcepacks/animated-items.pw.toml"
hash = "ba5dcd71dd9e075a20e0229edf807bcf14e54b62b7624fd47397dae6b7369787"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode-expansion.pw.toml"
hash = "990fdf9653a92aa992cda0bfbdeb05d177b22803fb17d1ed73c46c59a961199c"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "c907197b5684992cc022bb6e642682da984c6a742ea07766dc0c58fd0bdb7778"
metafile = true

[[files]]
file = "resourcepacks/pacp.pw.toml"
hash = "801d93b1caadb0430b781dfa081f8276b21dcc3683e5523016229bdcda6856d6"
metafile = true

[[files]]
file = "resourcepacks/williams-console-resources.pw.toml"
hash = "a9f6dcc9cebbb5843a1a77160c7b81701ae6df5cb0ff71d79d9baeef3c41f6ce"
metafile = true
