hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "8396310b4572149029a81cea139ea333123a68562f081184dd1359754973fc13"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "92deb5c02f7625e07c4e477c1d8cf3b1fb920e27aea38b45ed0c06c4c0e420fc"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "d651eafb669a2560b732b38a78dae72be74892e02773db07dfc999de9d6b92bf"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "d651eafb669a2560b732b38a78dae72be74892e02773db07dfc999de9d6b92bf"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "d651eafb669a2560b732b38a78dae72be74892e02773db07dfc999de9d6b92bf"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "6e599581cf0400b560021b7abf13202465d11bae611d210932fac5e1381b20af"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "989fb8f797a5a894f0cbf8bf529ac20c88cceee72384bdbeedd6a22d455199a3"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "de0e25757fb3fb538d710ba01b3ebe416e97f0b40b78af2749cb85ba138532f3"

[[files]]
file = "config/legacy/client_options.json"
hash = "291f7b347f97e67bbed5bd683e0ee49632a5a797427e3a167df29142826e30e9"

[[files]]
file = "config/legacy/common.json"
hash = "3b9b9361ed4ad964361358b210952bb01f4f30ff2d56c249d0ce517792244266"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8ffadf5901d31192638d4089d7b3eb16a6ed160252c9b4f7c6566448195f4019"

[[files]]
file = "config/legacy/global_packs.json"
hash = "b976dde04889f5828dd46337b44f4225779849af93f00960a6601da078249b9f"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "da9e16081492698179576b7dbfe7bf1e3fe5a44aa6ec8d14b17f9f0e6dd70341"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "da9e16081492698179576b7dbfe7bf1e3fe5a44aa6ec8d14b17f9f0e6dd70341"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/controlify.json"
hash = "bc7cfadfe7121fdbd356c7992705ea6f484de518d3fd473eb8c59ea93e79a04d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "dc238f208506f0dbf661be2b256207ecd0db586888ab7ad19629c84e5d239cbf"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "2bcd25f08afd77c9ec94392eef5762450a8b7d591356f93d04c19e89b5e56cba"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "5041d4be9d64017c7891f46878b7fa0d528c277e45c1d5e6be74b22abead7028"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5b9618476350398ad0d25b5bf3a41521dd015baa22e4bfe8db685625a3a2c697"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "bdaedb87300594cb776756286d7f615cba17a460e2b1e63de9f6881f44cb277e"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "3e0109bdcb98c740367fd5a2f455bea1d7663389266e3c34a237c5997a8c86b8"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "128d9dfd2156ffa54cea7621d3c3c2ac42d9865b3363996c08c70c5a52af98d0"
metafile = true

[[files]]
file = "mods/better-nether-map.pw.toml"
hash = "6bff653df737689105dd5d343e91891e93ae8dfccccab27c74357b2e9fccc0eb"
metafile = true

[[files]]
file = "mods/celestria.pw.toml"
hash = "ace3cb69757c52aad4f1298ab67c9812ffaf3feff0c61e4c9a457f5dd7c87852"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
hash = "b64931c7cbe7e4466885659b3fca1939a3a1d144da6212b5cbf4c0ae1273dc76"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/clifftree.pw.toml"
hash = "3b949cce6366014cfb8166f94fa58880bf46854689740abb2798fe2aaeb8e739"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a112512699928e5504f2e826194c60881f949902fee6c6bef5f3539fcb90db75"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "bcfc21fed54ad91380bb168ac6af973b8af23bf138b36fd104da6ac8daa02779"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "351926bfc2654935b27c5e40cdcbaf83431660e08cee3aca4e8ae2bd25002575"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "578b663599a5687c8b96a7ed89af21eef3499f7daa20611d271701aa06ad6fe7"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "a07f5a28192fcedba35c2db7472b322b381827db29372393e9429ef13c056020"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "1350769c8b58f5e79ace1d873276da0043f619d8e71a3c7e18289794deb7fa2f"
metafile = true

[[files]]
file = "mods/custom-window-title.pw.toml"
hash = "09d3121e0f62df0f7543ec669a7d2465ccc257f8ece46eaa37c0d8597ec36c15"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "71314f7a5609378c77f372c31d2c501a330cc901c6e4f6e060d7f3095d362086"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "d1f561a89e7a4c5d98b6cbb25088ea2ad56ca1cff60118f2076912f49f8cfed3"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "36d26044eeb09dc7a9cfc9be1970f4e2fdca97a8d9e51dc211bb026d4b63aa6a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "a4b817f8c3de5af3a6ecb2b72caa2daa3042c1e65cc8eb3c794a0b3ec3bbf847"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "7337f3f8447a07c0f105051414e88f45e0e194c13b99040e8d3d57c977fa5c05"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9ee84bdf71ae7963fabc99e8bb44acb72334d281b02ddac913e25daf7b81c143"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "8d6cb7e5cd8619b40c77903bc0be7178caa88cef4521559e6dec38d21471bbef"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "65bb8ced1d1f0db51dad9d5f22d433a203b53dcbccfce7abf19b530ace9b6ded"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "69c5ae686703cc74e092591cd5a1939bd5cc2e8522f928c77a77ab803be5e77e"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4387abb74dcfc93f9381c109fe76e7161ca7a91a1a642db4781b47f650c4ddab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "0ac4faa43fa6348191b94dfc7c0ed8a1b09f6dc3b36837b029aa023853019503"
metafile = true

[[files]]
file = "mods/fog.pw.toml"
hash = "17d991a9d3adc2f923bccf4bde22e648a6964c4934a2eee2f822e67345dc96fe"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
hash = "5f6ac813d736ea01425bf7c01612df6017e6a9ab465b39a341630ef1f6e05834"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "c73fc3680d04bd42fafb0ac3e5e2dfc9e50cff44453ecf91b1bebca6da5107eb"
metafile = true

[[files]]
file = "mods/hearths.pw.toml"
hash = "55f92a03df046f1ee4da2100025726e166576d47378932b685c56b9ff3da2a37"
metafile = true

[[files]]
file = "mods/ibo.pw.toml"
hash = "e9e790bd59966aad6d1c0d20eaae78d899974a5d2c0b4d0fab600ba51712ad2d"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "89ea2d0411426f6ae2e70b18b6421096fae6c3ab4b6e68387f5316d4f3e9b1ca"
metafile = true

[[files]]
file = "mods/infinite-music.pw.toml"
hash = "aa9fb2485ad1a63019f66743d0fb32f513e2d43ad1f2346c32494ba58962caa8"
metafile = true

[[files]]
file = "mods/inmis.pw.toml"
hash = "bed0c20b163868a1a87743127d229e0e8e0756b58fb68af47e83d89c68842aea"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d503a6ed4c0571f9ff04a67900e5f8307f1161a47767363bd343ee24817e6460"
metafile = true

[[files]]
file = "mods/legacy-mipmaps.pw.toml"
hash = "1495cab2309ad61ce077cbc7603a255f07a06208e08d2b176dd5ec7216cdda3a"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "cd55593e129301fa89dc8751ce917157f256a6bf0f5056ab9c37875acc6fc768"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "dce9caabe87f4b80fd7566d0b773fd69ef122866eaa5bd51ba1b077ba163d276"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "972db8c2fec6fb2f3545554062d4cd19364778e30d8f079221fe0d459efa8517"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "ce7c5b0a5fec7fed7dd652737d88602d1a5421f1b49aeea083243b141efff0ac"
metafile = true

[[files]]
file = "mods/map-tooltip.pw.toml"
hash = "c0698b5fbb8d41c069f4c9099a17e4c01592b645c5d38731496251b0e985f6ff"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "0f9a9042aaea1f95a68c87325715308564ad6b173437dbcc3f7ac1c63d71b87d"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d2eef785df399c7b45f20ecc3d07e1749b4bff2b2f87dc1c47d3a339996569c2"
metafile = true

[[files]]
file = "mods/mru.pw.toml"
hash = "0aa27cfe48f3b4a1a485e6fddeb5d806301204130ac51a1352abc10cb05ca1aa"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "93c5b81a82fffca423eaae73c4ebd729b8d644aad0e35eda39c287f9778fc9a3"
metafile = true

[[files]]
file = "mods/netherite-extras.pw.toml"
hash = "73b781d385f2bbd54dd38b33987e63012c8113f81eb874d1d8e4c69d358103a1"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "537bdd1937193d94cf47f2232e2b38357415e5af8c950d97661b3ae881adbb4e"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "5856f4957a831c7c1fcef292186d3bfdbf29696bf541d2621544e3bec1265b02"
metafile = true

[[files]]
file = "mods/nostalgic-tweaks.pw.toml"
hash = "ee92e804c6ffd6509e621421b9906efa0f654885053b1ea00c7e4a4eb55dae17"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "a6e3ca19c98f18fcf6e8a89587c0fb15df4a2147db9ae1f18d3d2b178fce10ac"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "3ecb49498a9bfd8fb1f980236dbca36d42d5b458f539770b4b4124ffad9d76b5"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "e738806b1099f2b4b950ec57816582f3b7afd7a0074a250e3f120aa78350bc7e"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "58e380b4d66907130eaa480252def925457d1033100571c946aaf9179a1e7bde"
metafile = true

[[files]]
file = "mods/qdaa.pw.toml"
hash = "72849c84af6ec19ce9138e65fc855e929fd53a1293234a466acb76cffe205dbf"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/resolution-control-plus-plus.pw.toml"
hash = "49b4b01eb3aae1cd5c78da42945be2635d4adfe525404fdc046c8bf73d9f8b34"
metafile = true

[[files]]
file = "mods/satin-free-wakes.pw.toml"
hash = "942a559e8d8a13eb9f2864855b6afd48b862669adc4e9a15327c57f3753ed677"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "a031862c777660b5e446d10b7a8891b42c5542719268873f8e170b01edbc409d"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "461adc31ce2b89cafc5ad2e846b482c68529231ac1d907e39ec62458b22e6b3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "0a6179657082b15117e18fbc80fd60538dc91024a63006e843cb5dbf1991bcbe"
metafile = true

[[files]]
file = "mods/sparsestructures.pw.toml"
hash = "97ee05a5cd4200d301cd26a50b0ee88c85cc00336732983e383efc3a6fa2da41"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "784d31c38a90243c105fcbb5c7ccaae37c920eb91a4637b1f2dfb268ae1af4ee"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "0dd2dbd4f1696ba345ecb91fdf6cb8e4273a5c430d6395181bf392db98cf23da"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "125171299b2cd518eb3a27bb421ff39e5580b1eac900c9498df1d1a3cdb7a865"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "a60a3daa425e1d278d5a51abc60d3818979278970559ee1d392757c0b3e4f50b"
metafile = true

[[files]]
file = "mods/worldgen-patches.pw.toml"
hash = "a39b36424f533c3782535b2e47fde1fb3f26eb60eb11f2fef411910d0cec0e62"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "052b70117c2e9a3a697a36f449b220be7bfba215f3a2e43b5ce7faff9e88b2e6"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "c907197b5684992cc022bb6e642682da984c6a742ea07766dc0c58fd0bdb7778"
metafile = true

[[files]]
file = "resourcepacks/pacp.pw.toml"
hash = "801d93b1caadb0430b781dfa081f8276b21dcc3683e5523016229bdcda6856d6"
metafile = true

[[files]]
file = "resourcepacks/williams-console-resources.pw.toml"
hash = "a9f6dcc9cebbb5843a1a77160c7b81701ae6df5cb0ff71d79d9baeef3c41f6ce"
metafile = true
