hash-format = "sha256"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "de0e25757fb3fb538d710ba01b3ebe416e97f0b40b78af2749cb85ba138532f3"

[[files]]
file = "config/legacy/client_options.json"
hash = "4727eed255722ddd13ade6cf28a3714000b3d45f4cd816e23237a89242e065f6"

[[files]]
file = "config/legacy/common.json"
hash = "3b9b9361ed4ad964361358b210952bb01f4f30ff2d56c249d0ce517792244266"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8ffadf5901d31192638d4089d7b3eb16a6ed160252c9b4f7c6566448195f4019"

[[files]]
file = "config/legacy/global_packs.json"
hash = "9e247f86405d42e83a3e1af74984e4bd4cf64cc3e357de1821df3516cafa7ff7"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "219204a2efc6d53ad8b3116db7392e039ba8e0ed5f45bc18562c9697bdf8f5c9"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "0d0549563aca08c87a22a9fd862cc6e7a9906f2d6fca84dcbfa7cbec14dff7e6"

[[files]]
file = "config/yosbr/options.txt"
hash = "cfd15bd7cf3b9570c62f5d909136c886a3da3ca71f3dd1b2fb90d4ed21852452"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "57c157ebf3f36495fa14668c3906e70726a83564c7d0071507fc85baa106626c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "acd54752b9c03223637a654249fcddd06a0a82e9c5057779ae6b8bf9213a8a5b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "6776faa0af7b67803be2671ebc8c8d25f3ebbdb498cf7457b8bf6baea65a5f9b"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "058798a2c892733565bbd4b5566743b0305bdaa6d2c4237a98ec432e4cd96c4e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "12d88ff814663555fb216d47884a166374a76210ea7c75814daa6e897203abbf"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "c574545ff4b543e80c299b38cb5830246bbe9c57a63322d30e2c5355848f812a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b145e5dd9741ce6de8408c8c60f9a657f02fd417ddf710a87f2af506b6297256"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8b481b1845bb190388182a683a4efe506516429ede29757923f48eba2e1a43e4"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "d1c6fb3ff44ec99260611c3379a2332097d0d05fa12ad6000691fa3c52e99a3c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5773d3e597b591a9cd1d6d0808aa5820ecfef9f95c3ebe88aae485980f032e8a"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "08e7fcbf0eb89fd14ebbbe9f041c60c5b5cd63e5554386766b6ef7476e7ed65a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "bc5b833dac6b91f96e3d650e1209d141b9267ce7cb7ac45b8b5a976d6c6a5f4e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "76d79c4c09c4b862ce82cc0cfee5ee4f01222c1968586ba68d9435767aecfcd8"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "cf94bc56469384fddaf2138fdfa3c6881ac1035c5ecf282e2bb1ba7bddd79996"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "9243fdbcadf7f6bf5a32f2b73e50ce7d374f99b685a7d1d5cf77c1ec76f60c46"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "e2df68f4727281ba97abbde12f3776ff9edf1b2ee67e36e30a25170ae0090e34"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "152b56e4569df781f25328326e4cb0e479f4c4326a7249b498cf45512fc2d46b"
metafile = true
