hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "790a6d1948c92cb564f62cf1085331050f3dcf4e2edecb0740aded07e5357e71"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "config/yosbr/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "config/yosbr/resource_albums.json"
hash = "ecd81924a3b2ad635ddbeef550da86d325300a88ecd133daa70de8c3ed6c9242"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "2eb94ea8666cbff60ae65f58198d135171cf85ea2b9511fe90a8ae1b3285fc0a"

[[files]]
file = "config/yosbr/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1c454e4b4356588b9929a48976b4f2ceb16f89fed41e557a8e72c17ab005ef43"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e36c1c366932cd1891d6bf35635e5646e8e9c2ef5f900dd534479a8261fb894d"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "24760ba6ebb2662f152661f7dc8401f58c85b3818f8163be39e81d5e47440513"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "b707178eec094c3e6ba569818a746a73f54dd50c73e75fd4cf720336e151cf28"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "b9f3125089b6f601a92f0d9145852b22d7af15425fecff9396de3e457aaa2740"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "96ae3258e9edf61f653d576a4909df889ffdafb49d0acb475d545c19c8485930"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "fb97a08f73b3ac92c81e10091e046968d83ec53bb012a87d1e732d53f0a881f8"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "46a4a12d527e643b378709dae0cc07067a99b4857c68242516b71fb6cb9bb398"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "bceaa795c5bbc0e85650981883634ed7cbc9535e2bd69a825a42c5fbc9d227b6"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "28f6a6d8e6f7165af6ae223a4e066209696064a5a18d587d8c1e6450df597e70"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "db6307345e7a8c285b6f244e1dd0904518f07823dcb923d2ed973097895cc643"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "17c7f089a4aac6d14709af2ae562c6b090359454a5cf8b0a0a19c68553d4be9b"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "07a2d27d95210a8339434a78113461e1fffea0f039001e117375cb9d99fd6971"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0ff3279e2fd6dcb9fd06189b0976f8a10133ebfc28895431f077dd7cf7f82176"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "92c362a4e1e0bd5addf47fa90a54591acd0cc314063225b193f5f03df35753c5"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "5d27e02dca8c1e2d4a1b473f92a62cf2729a03eb2ae245f25c37357592519eac"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3dcc43cbc807ec49377efe574b4670ee91e62474aee1bcd068495adea8bc1f6a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a43a1738f3627bb2182874c34dd53fc7ccb6c0f431dd4366a09b1a1cf49debc0"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "380029e996bcd7d1ed8149d3645899d0f6c1b72e3228a1a9f159404f6dc74209"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "0c94cbc1c3b8fd22640b944f0afb9f6210d78aeb11d6c3d1540088a9af1448fe"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "6da10c6472aa024241d87c9a18da016e38561e4f45627f3986c58029d67dde44"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d623f18ea127019468abdccd43c3aefd47629543ecabc61ffa1e62e39ab614c2"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "6097580eb9efc667d660fa9812c2fe8f7f293bd1c1b99fd473c954a2c99c34f4"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "d5878a8ca826374957a4c4675a9e7dda82192d03a905a927e807b0c3c8488cc6"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e42e9478d889222075b8fc20a9d934520fe153471d388fe5291d29d7ceef0c81"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "cf67478fa85704ae65c89536a4b266a498c0d8dde4e70cbb67e83a4e9529cfff"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f05065dc4940c2cd03f23a9a808fc3f496a167503fcccd2d1106fdc8e09f30dd"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "5071e2db016a635fd5906b341c1c9cd05ccba6a260f3bfff9ac7f7647c1ff080"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "df37a0309e63a859e93355aebd0ded00ec5a4c03dabdd1825b5b2ad5a743cb19"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "045109bfa8ee556c696a8abfa1751242b3bf5a601773f0fe5572238e5f8f3856"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "2d9cbac14941fb502ff87e223201e8bf98a4c249b31b5a4be3e13cf6c81eaf69"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "588532fbbecdfae0d555acf919f0281e8371a471caf2458171a839592d816d05"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "d0ccbaa4644c53c68a852887529ad3a3843817f6d8540966ae790c6c7ebc4d1c"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "3e30a977c606f6d7be69e3db61fd147aa48c633fbceefa91e0223fbf493db41b"
metafile = true

[[files]]
file = "servers.dat"
hash = "fd4962951c610748761e3d1530542dd02bfd3e94cf5a5bbad74fca31e9d4359f"
