hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "eacb246be3c5af4b7acc99a26403c39e2c9c18f3a327f0d16c639f449d32d008"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "config/yosbr/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "config/yosbr/resource_albums.json"
hash = "1f8d93804a395403fb745539a18895edf83bddfc4279facb400dfe97b24a9172"

[[files]]
file = "config/yosbr/resource_albums/adventuretime.json"
hash = "4c1f9e040d4ae81146842cf1d740f73a5829ae5a94bbc99f079056c3b614b010"

[[files]]
file = "config/yosbr/resource_albums/candy.json"
hash = "416f6a75a65f4829f78c2d6d7f213c55c2500d878417bc87e26b4e45b11bb2da"

[[files]]
file = "config/yosbr/resource_albums/cartoon.json"
hash = "3e3232b63e6117ab58ebc4a612390f6f7be7e70d6b484bb1d10068d3a5d5d199"

[[files]]
file = "config/yosbr/resource_albums/china.json"
hash = "8fa7cc8e27a3d8b08dc6a1c1a541764d96ace4e218a53d88d9a1d7f656c9d0b8"

[[files]]
file = "config/yosbr/resource_albums/city.json"
hash = "f2c06613befac8ed4caaece29757a0c70e7162d07142293ea75ff8f9d2e824a9"

[[files]]
file = "config/yosbr/resource_albums/dark-mode.json"
hash = "148001ed77659ae269d34ae7b29a6da34fe8914458ed2f50f7f108a693f6d433"

[[files]]
file = "config/yosbr/resource_albums/faithful.json"
hash = "79fb5e2fd4382e9bff8d3932c10f8dbfe77d120d333cbf2a41c12769d159f38e"

[[files]]
file = "config/yosbr/resource_albums/fantasy.json"
hash = "0404baa486631c6a3ca2599f9bca14810f699075666b8125fa4dffa41e76c446"

[[files]]
file = "config/yosbr/resource_albums/festive.json"
hash = "2f4c85f261d138301e31984883fe0210633bd5e4cd00130f7489eb3861b1f9d0"

[[files]]
file = "config/yosbr/resource_albums/greek.json"
hash = "004eb5c2f6fef1026da173033df9de2027fe392dd825848c2623279aeca9008f"

[[files]]
file = "config/yosbr/resource_albums/halloween.json"
hash = "a6a7f13005787fe4f0ba5fe26f509164005209934e2b82508f770fe09fa27b56"

[[files]]
file = "config/yosbr/resource_albums/masseffect.json"
hash = "e5270528a4bdc3887fb8ad39393cb6cb0c1fe4711e31df4d51576165531a048c"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "2eb94ea8666cbff60ae65f58198d135171cf85ea2b9511fe90a8ae1b3285fc0a"

[[files]]
file = "config/yosbr/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "config/yosbr/resource_albums/natural.json"
hash = "ca0740f2074ca858cc1bedc0d69b4d1f8e4803d611eb1afc6c8767b14035dcee"

[[files]]
file = "config/yosbr/resource_albums/nmbc.json"
hash = "c5c9d1037eff862068c67e4edbde9cf0f78cfe30e95550d0dcfbda78dd4b6193"

[[files]]
file = "config/yosbr/resource_albums/norse.json"
hash = "6602e3108ac964cfc8b1b6b6076475432f371ee6b8ae9a8265d08519e23f6664"

[[files]]
file = "config/yosbr/resource_albums/pattern.json"
hash = "d7c5e175e75969bd9c66e2a1c44e03cb4e181c758e650a9f1e98d26bc70a193f"

[[files]]
file = "config/yosbr/resource_albums/pirate.json"
hash = "3637b092d60be4607535585afd2ce71caa392ea1638d5477740eb35fb5102713"

[[files]]
file = "config/yosbr/resource_albums/ps4-parity.json"
hash = "5fb6819bbe4db2fe6795043a8deb63e0314ac493c659897ebaa5180385a59bb1"

[[files]]
file = "config/yosbr/resource_albums/sctp.json"
hash = "d6fc93439481f825a2f90e98851d02627d8e9a112f501212b4029258c7ecb7ab"

[[files]]
file = "config/yosbr/resource_albums/skyrim.json"
hash = "979b8dee04776bab2990a88abedddfa933c07cff1cb90ccae6c9a25d72306459"

[[files]]
file = "config/yosbr/resource_albums/supermario.json"
hash = "f202b8dfefe7a3b69177c1ca51bcd541f2863d858e0330718d1b125b4d08f8e6"

[[files]]
file = "config/yosbr/resource_albums/toystory.json"
hash = "b0567ca4e7886edbd0c5e4e594a18f835450905cf18abb3e943fb784c945ea00"

[[files]]
file = "config/yosbr/resource_albums/trailer.json"
hash = "0b87f64e788258d1d8a3f2e5117dd0f98641fd0d55cf7ae266e92fa048e712fd"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ce27d4ae4d82eee89e616d19d13827205a2e26aed72a6f2e70bc409829603e01"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "57c157ebf3f36495fa14668c3906e70726a83564c7d0071507fc85baa106626c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "e1c3c11ad9cbbbde3954377f7b40a3044ab1516384eebe6173c08b64db87bd03"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "c3960a9aea11d9c0d8d5a683e79a0ddb5db0911104379f419b9a45162a30e820"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "968e034ef709aa283c9ae488eb3f7a532c779aa9b4651b0f544cf530602dbbfd"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "cc7f6dfb40f00d0adec740d5feafd86a64cf08a48fdbc0dfc2b10bb9c904b8c3"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "aad40869895f4d5543056db4672ce0497cb3d8a64c815b13b950c726e1ab41ed"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "0f2372aecbfea9d4c36fc5af1a2cfb577cd1931204399821cd9045d9d59d642f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "588128c093c04c8b408799e2c0c22eb87b2ba34ce128312eeb8ce452c6111a67"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "527909620de6267bd68b382754c0e7f3607df7aedda1f08dcdf001bc955d015c"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "9b81c40c85a0c9f73d73fd7b9073a7b10d141c69c246880acf810fbb14e1dc69"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "08c1d9e819e1b72fe8bfcc265879f2b65d3dd97bfccbf56d946ad4232c521693"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "e2cafe9c2bdee361c8fd5ff8b09355f3834fe11662a8b9994e72d7d0a3fa2388"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
hash = "ef2b0bd0c67b08e9e4e081566e87139b43ce5d3609cd3c6f7fa345bcf3a48fab"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "076a7e957446c8ec4af729b1c0f6ef959634c8b838cf288440998b4d0c5359d7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "c63d74160e337597c5c5cd8b33146c7fbbe1763dc84277700cd016f7d1b51590"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "ded2249789352333403a89b2e398fc266f703d5cd7031ec7808294de70bf1778"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ce9ae929096c3574a392e27efff728f2a07e65ed2b9dcc5d6c861590b5ab5dfb"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8b481b1845bb190388182a683a4efe506516429ede29757923f48eba2e1a43e4"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "dbc7c881a5054466903b8bc3471aaf5fb0228f104de1537cfbdffffa0306d730"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "0d980618942b45cde9b927fe57c68fd76bfe17b69cd9c7419f0c23541fb941a3"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "2b6d6dd18816176024a92d5793b12ce3a62cd0c4b0cf31fc92bb59058444a303"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "0e3ddf37c5eeb90e1dfdc23338f5f465654bb73cfbb0be32f64061918903f2ac"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "d5878a8ca826374957a4c4675a9e7dda82192d03a905a927e807b0c3c8488cc6"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "ae01096697bd442dd7433238190677f0062d418981cb8f7a48a993d41dda2667"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "3ade9bf062256c4205299e64086552f92170cb06ff5b43dccfea583aaee757ec"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "d5062c588f61ce1daf34dfa82335a70f9b84f6c61cc290ba6e703c809f95980b"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "7ffbcd92d64deaf3b9a455870af3413f1f9ba39bd039b3733aed3eb047e9264c"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "da8f21ca9c35c760444aaf6013d93801930bde6e530a8faef7f3c4946e4cc0ed"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "94b5f82ee337144ba05d83ca775a5db4edbcba6a02b959b6831d08db66b1a50f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c6a0ba7e512020ee5461dfefbb1d6b15c2dd336e4084bbdb5b7facb65b923a"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "2d2ae2215bc1baea399b60a9b7e0bd657d79e29c5c86861ee36aae1864786f38"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "bc5b833dac6b91f96e3d650e1209d141b9267ce7cb7ac45b8b5a976d6c6a5f4e"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "dde747307329310e4c1cf5380c3890828c6601b5870a2f5390bd9048c25fb8c9"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "19708bd773a1327dea8bcc02b20cf43ec904a8ca18584dadf2e681893d0a539f"
metafile = true

[[files]]
file = "resourcepacks/adventure-time-mash-up.pw.toml"
hash = "402197dd4e27f3bd22a3235c2a44b7f932419156e0d5621b6dbd83a05918e9fc"
metafile = true

[[files]]
file = "resourcepacks/bare-bones.pw.toml"
hash = "04a01e87e47ab83938d7a174c6260dc0d944ec5f2dceecec0cfbcb85b8c7d8b8"
metafile = true

[[files]]
file = "resourcepacks/candy-texture-pack.pw.toml"
hash = "bf5f537c51084a326b5b4f0e4b78b324af0c80d560348ccc81c500ceb2b3dbf8"
metafile = true

[[files]]
file = "resourcepacks/cartoon-texture-pack.pw.toml"
hash = "f77cfb206b291303d6b16c765cc6a09b9114ceaa4210e6f8d8f00917f8fa9622"
metafile = true

[[files]]
file = "resourcepacks/chinese-mythology-mash-up.pw.toml"
hash = "efde47d0d91609b82948cf74c40a87a727c56684a1a50ef1a2efeff23605a3aa"
metafile = true

[[files]]
file = "resourcepacks/city-texture-pack.pw.toml"
hash = "cd28517878a0782576343823bb744745beeb0067a728f2e5bfe4608a49bb0b65"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode-expansion.pw.toml"
hash = "7dfce4ccecce8e51ccfd8c49d580e446dfb1480cf988dfd2dade9f11e590d01b"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "4d54a64972ea89e49f314867802406f7ca73fa738ff35320c938f980ac0c8f4b"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "54443027f9790a0afd476a208bad68a52f05f988bf6e72095a0c3056d8fd7273"
metafile = true

[[files]]
file = "resourcepacks/faithful-64x.pw.toml"
hash = "474a40c596e75cdc82ce1e2e184d7f0a3c448e3aa90ee0ae8c649ff7a10879ef"
metafile = true

[[files]]
file = "resourcepacks/faithful-legacy.pw.toml"
hash = "e0e2a38f191b57c82dd418388b9a16661d6e4ee2322187c504ef5a0d13b36186"
metafile = true

[[files]]
file = "resourcepacks/fantasy-texture-pack.pw.toml"
hash = "6bab01787361072d717e02ed0830d38f28d2cc95421748f081c1f39fbeb25d25"
metafile = true

[[files]]
file = "resourcepacks/festive-mash-up.pw.toml"
hash = "06bb57a0de16fca9f735a0791da22d391468f6654a6e2569a428dad2d9255721"
metafile = true

[[files]]
file = "resourcepacks/golden-days.pw.toml"
hash = "387b644d037fc780957540afd3fcf6889aa3c6be8f895fbe6eef41dd8772762c"
metafile = true

[[files]]
file = "resourcepacks/greek-mythology-mash-up.pw.toml"
hash = "8116e83b0374bddf299d5d673726a1f66fdfcf0cf338a26f65ab882c66b2a144"
metafile = true

[[files]]
file = "resourcepacks/halloween-mash-up.pw.toml"
hash = "65aad6efd72bf1297c624379a1a3834cfac790edda8286c931be9de5522d7ff8"
metafile = true

[[files]]
file = "resourcepacks/lce-panorama-collection.pw.toml"
hash = "7946b3c1c7c3293f89048833389c449e75f43b87ccc27d156c7e91b0d92aae31"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "3c078794557a1ce93476771bbcf61306d82824d11621f08152396904fe8e45bc"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "9243fdbcadf7f6bf5a32f2b73e50ce7d374f99b685a7d1d5cf77c1ec76f60c46"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "aed5efab46de12e572df2b7f73173d7536552b941d796ca7afea7d8218c6afa1"
metafile = true

[[files]]
file = "resourcepacks/mash-up-addon.pw.toml"
hash = "e7fa8a04fe568d61c6efd106c9fcc37cf69e7222c163789a4eb94f7566d34aa9"
metafile = true

[[files]]
file = "resourcepacks/mass-effect-mash-up.pw.toml"
hash = "e80ce3af117b1634a4c9b6caee8fc5abbe82a36874a53f6da7d9dd5c8f87fcbf"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "94fd733b190559644dec07baaf39956854bdd510a2854e3bbbdfab6eb92d9b5c"
metafile = true

[[files]]
file = "resourcepacks/natural-texture-pack.pw.toml"
hash = "2fb042cece595e725830b539896ca27167c16d6e94180749c433c2fc240086a9"
metafile = true

[[files]]
file = "resourcepacks/norse-mythology-mash-up.pw.toml"
hash = "fd6727df8d5cf7dfbb531628c39d28dbf41517119305d0380b6771481f025f3e"
metafile = true

[[files]]
file = "resourcepacks/ore4j.pw.toml"
hash = "89b29fa9099f6b9303798b4d232f0b818edaba2ba30d4c97e9c99c8bc19ad9b1"
metafile = true

[[files]]
file = "resourcepacks/pacp.pw.toml"
hash = "1b2ee42699e928ceaedd271ef9e64d87057518b84f90d25c21d2b616f1cb8209"
metafile = true

[[files]]
file = "resourcepacks/pattern-texture-pack.pw.toml"
hash = "296aa718e18d2956304a18eb9e33d7e27bec172a45323916ebaf969c49a9e092"
metafile = true

[[files]]
file = "resourcepacks/pirates-of-the-caribbean-mash-up.pw.toml"
hash = "236d9566e71bdb2e102bad180d8d8c5519b28bef5d3c830dee627d2d6f6fa1a1"
metafile = true

[[files]]
file = "resourcepacks/plastic-texture-pack.pw.toml"
hash = "9101021769de310aceed0b321ab469e09299fdd83a358d5c1103d44e5272b801"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "1c3e06c2051f59e8c258e93230ccaeab3894b7e3d20e46afbcde18b1216e388f"
metafile = true

[[files]]
file = "resourcepacks/skyrim-mash-up.pw.toml"
hash = "d01ba23c2848a63573037d2766e7850c53c94e06f9897a7a89f5083001390c74"
metafile = true

[[files]]
file = "resourcepacks/super-cute.pw.toml"
hash = "bb9ec55a30673b56c02549616dfdd7454028f563aa91f048b0bef722bf4ef5b7"
metafile = true

[[files]]
file = "resourcepacks/super-mario-mash-up.pw.toml"
hash = "071f1d112077ace598834a46cc6988d5e98e9bdcbf98404d1d64fcb46482dfd6"
metafile = true

[[files]]
file = "resourcepacks/the-garden-awakens-skin-pack.pw.toml"
hash = "73ce3f2f8aed02f522b567a66f17d441c4b4d9a04bb4def0dc9d8f4547e90f21"
metafile = true

[[files]]
file = "resourcepacks/the-nightmare-before-christmas.pw.toml"
hash = "a5d56291a5b2b75eb59585647cb45226bbb3f8746588de9123690a8da10dcfa7"
metafile = true

[[files]]
file = "resourcepacks/toy-story-mash-up.pw.toml"
hash = "29ff90f8fe98654f313f8f1bf0c47755123e7d5d3e3810d712c383b5a6dda6e7"
metafile = true

[[files]]
file = "resourcepacks/tu5-tutorial-world-panorama.pw.toml"
hash = "f8844305bd6923211c196511017448a9891efa28fd8b941dbf6fa5157058c798"
metafile = true

[[files]]
file = "resourcepacks/tutorial-world-addon.pw.toml"
hash = "94d9ef20d83c22605b83346ea9514468cc27417d4f26b504cc4e5bbb90364a04"
metafile = true

[[files]]
file = "servers.dat"
hash = "fd4962951c610748761e3d1530542dd02bfd3e94cf5a5bbad74fca31e9d4359f"
