name = "Re-Console"
author = "omo50"
version = "2.2.0+mc1.21.5+neoforged"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23c0e0c6d96b3a58ecb5e10d41bd0437fcbcc18048ef1cf8611570e94cdb17a6"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.75"
