hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "8af063ed80c9805b95a56a125b4a6ef3899d7a08c2d882fda989436cdfd02cbd"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "config/yosbr/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "config/yosbr/resource_albums.json"
hash = "ecd81924a3b2ad635ddbeef550da86d325300a88ecd133daa70de8c3ed6c9242"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "2eb94ea8666cbff60ae65f58198d135171cf85ea2b9511fe90a8ae1b3285fc0a"

[[files]]
file = "config/yosbr/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "017ef5c4a67c0e11de2fbadf1aa91a9147f2c39a91ad52f09e5fdde9d8cfcfcc"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e36c1c366932cd1891d6bf35635e5646e8e9c2ef5f900dd534479a8261fb894d"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "073e70df1ab0c4353e8d13042b95949311f670fbfa3a3b056dcb421227ecc967"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "dc0fd13cc9842ed2744ea571083294be30565473d2a3e88787d5f8604a5d1b29"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "8ba08e4eee0cc3b4800e83d45a2a3222d91b22f3251936f8f638709d6f529c43"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "759225faa85e3112ff935bba420bdde12ff766c848735e27a87920ae6ba61b4e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "41ce2ceb6374c5db27705af6a8dae1fa82b9c522e6ba75dc1a0ebb8cc23f44d4"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "27e2e05cfc8c553355ed06636b6820463ca2ee39a1a26d5c4ff8d2322e185969"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "d290bb6a7551ed5454d079ab99d2997669b3cbafa491ce67ce24072f35b8a9e9"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a65c7114e3d56277e74f4426ca5b9a76e0d910daa3abd1a093d72893ad2ddf6d"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "d1f01cb97ef983b086e94948ce094cdbf2e410fc4f7b0c6fc0a96585aa77c610"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "dbdf07684c81762c884b2350e0b925acfa44c8b531392d2cc1b8d492d2c90db4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "efe2c454271e788e53a0b67b599b2990a027505e67c1b73cdba8109558442d6c"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "faf2b5f96b2388c18aacab52b618baedb43c8b5b79a8d29b3469634ff11a13c2"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "24a7357ffb04ae3d8ec4add4fdf99fcb10e369ca5cb98eff78b937ea2a2c2f45"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "9d0915eff742fe8717c7297b6cbc3d915ff33d5eadabc2a8a52d501238ea7097"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "128522940ecdb7c4c95dc39afe7b2f8c6de7da9a5de2f6944da38f23f36c647f"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "92c362a4e1e0bd5addf47fa90a54591acd0cc314063225b193f5f03df35753c5"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "f03f35181b728a6e19fe59754b52b50ef5c07e9389930516bfc7b870ed9f9317"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "1b55be03901c2270ab1e349a8922b80546542637115b7d5035f12ad197378409"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "cbcee3ba79c50de55d65927e3e3454f359f36c4366ba9c62e6d2dd20304ff096"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "fa32f4a5065ebec1bb6febd9a4d5f3f42986b502c7374f6997d32988546c1436"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "4b18eb3f964a34971bb1e695f3c9440a943913db4b72dca51730e2754b2f1866"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "ed93e4e4ba3fc19f50bee7cfe8b595197ac4a9c0d3bb9553c91941e27e9e7f0a"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "7bd6acb48a7be4b962a533fdee6a1449f9c137e725f02df2a40194dc1be48142"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "cadea9f04ab2eccaca71b364ba24e8304950f5b70182ea1bbf6484e9df270c04"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "fb55b275ecab408b658436048daab0550afe169e60105dca70d1648026e385fa"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "792a5f0fe941e7c9175cb7234b025c1e661a65f3d7272c1fc4cf8cea4015036e"
metafile = true

[[files]]
file = "mods/model-gap-fix.pw.toml"
hash = "f177093f7b7b0c705ff62449fd353fce870e20ebf0eedf401cf30a0e08f669bb"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "064418cb6d530c800bb3b6d8cc80a2d22dcefe49f8c7158fe362fa2941eef19f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "7b476b269a9332a4351b86ee0041c44ec80ced0cd2bc7a24ea0a774fbe39076f"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "cb86fb402262d14ea3d037c6ff1fe5b27a19420da13070ff724062a17ac62dc5"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "e9ebd6568d2680107f47d4bb2269131a4871d5242c9c9f2101022d4ae1cb6ddf"
metafile = true

[[files]]
file = "mods/moremcmeta-fabric.pw.toml"
hash = "6641c6240c695938707f7d02afff2eaf6298dc3fc7c8b6e6ec79d531e6cf6e20"
metafile = true

[[files]]
file = "mods/moremcmeta.pw.toml"
hash = "874a6cc4a8617f0e909449da4edb9b50e5ade6d6fc1dbdf0489a4af31d9e2bbc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1c2b5d5abe012ad2908c2e685ca7c1f90ef6579c7aa5838a287641a5f1aef00b"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "9e7861f54a7de6b065ffd247fc72aa67f98359d90e33c44cffdc2b6dee765c4a"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "1494bb9bc579f76b1e44d42eabd00bae3f17d83373eedb8e7dd79e8171d574ac"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "1c34733124a0547e2262da006c2e907fc5a02af1098f67f8e975becc8e8ecb1d"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "89f9cd95e900717c3363a456e5c7cb92ccc959f323300697320bed3dfd06e935"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "c5a272789226032f3e54cc5119159f66e00c862ab2671c52186d9509e20c56d7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "16ef040dd183e6fa03733b38694fbcf59211e50096bd34a760559f8d06a0c63a"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c757c1e3d5d1a887143e727f7bf7603a8c653bb0d58a4e0aaa3d3b24cce99680"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "7df2d4d2ac97121963c3f78b676bfb48d78ce788e10a18cf626611e00be4d15e"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "4b34d0b0a337960b15a16b5cb57081f0eb76bf408c0670b8238d0bf713226dbe"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "38567fc1ee72b6f114f96ad1063d982066b214761c11ba4894e5a008546047ab"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "3e30a977c606f6d7be69e3db61fd147aa48c633fbceefa91e0223fbf493db41b"
metafile = true
