hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "8af063ed80c9805b95a56a125b4a6ef3899d7a08c2d882fda989436cdfd02cbd"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "config/yosbr/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "config/yosbr/resource_albums.json"
hash = "ecd81924a3b2ad635ddbeef550da86d325300a88ecd133daa70de8c3ed6c9242"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "2eb94ea8666cbff60ae65f58198d135171cf85ea2b9511fe90a8ae1b3285fc0a"

[[files]]
file = "config/yosbr/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "f6d959f9e7d1589110a995fe01655183ad9ccae0998ef2f93f8ea40fd814d863"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "e36c1c366932cd1891d6bf35635e5646e8e9c2ef5f900dd534479a8261fb894d"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "24760ba6ebb2662f152661f7dc8401f58c85b3818f8163be39e81d5e47440513"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "b707178eec094c3e6ba569818a746a73f54dd50c73e75fd4cf720336e151cf28"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "b9f3125089b6f601a92f0d9145852b22d7af15425fecff9396de3e457aaa2740"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "27fb1d3f00be58a53bb181b763d645a31b6edab8b6f9f92f9cd2df8007ff8573"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "287209b1b1b7c27f11f59ef3eda5fb5f4431aa6b51701870a426c0b39da74fce"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "c16fb83b75a24f8e37d14661a3773db06b01a68b31d320659a0daf2fc88b52b7"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "7498e1251b64509ae70458fab7edd6121cdaeb197d9138bf38bfe7035e3efad5"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "28f6a6d8e6f7165af6ae223a4e066209696064a5a18d587d8c1e6450df597e70"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "a4f8c0dcad7e8b544b9da4e333880a4bae1701a3a06a7bdc8d85d12cae3276de"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "765905047905274de2bfca37b2866e986a6820221f300b061822a96fca203730"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d97557acca9a1943f5daa4fa8b7d3e86b8a2022af36c4703ebdb588020f689a2"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "7bfc044ef783a8f64da55b6319ce8299de6ce697f6cdb672331d4f00b4a938d1"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "29cc92e2f4586afd14ecb783779299b148c84f6e81b2e3cd346e8537e289b2be"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "92c362a4e1e0bd5addf47fa90a54591acd0cc314063225b193f5f03df35753c5"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "10ca18a3ecc1f43ed7e23c3483ef8823756744628fe59a7c32918106f81961b5"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "3dcc43cbc807ec49377efe574b4670ee91e62474aee1bcd068495adea8bc1f6a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "a4bb14a1fa7e05fb8105769df36e04d1214624350f68c1c2e2de012aabc80e33"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b15c3312a4cca50bf37dee2c669b8c52027b1264e4bd0800520471462596db24"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "0c94cbc1c3b8fd22640b944f0afb9f6210d78aeb11d6c3d1540088a9af1448fe"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "6180cf5bf5f3fdf1d4d793e5d6e7909bc95dc2231ad1a0d8df721e98367c921e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8ed3fb634ac434f95a729d138e7502acc16a006d1b8cb05ff67e39800c751a53"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "792a5f0fe941e7c9175cb7234b025c1e661a65f3d7272c1fc4cf8cea4015036e"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "3001478b4d0cb4cbb5e09fe8ee28724a1621780d4f8812c05883a32459339d92"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e42e9478d889222075b8fc20a9d934520fe153471d388fe5291d29d7ceef0c81"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "229d1eabf82bea64acb5421ff045294b895340fd4e44b80817b143a54d76126a"
metafile = true

[[files]]
file = "mods/moremcmeta-fabric.pw.toml"
hash = "6641c6240c695938707f7d02afff2eaf6298dc3fc7c8b6e6ec79d531e6cf6e20"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "18dff91854c7f4e35080dff12f68c3572b1670ff4e8406babcb3bd9264d3d369"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "0efd7e14dc0dc2273f1d14a3b1f555dbbab334ecc2fffa495e2c7fddda7404b4"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "f05065dc4940c2cd03f23a9a808fc3f496a167503fcccd2d1106fdc8e09f30dd"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "f983f8305bbb8eb0b9759e306b5fc366306dc85183822d6f10851299f9802470"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4fae11d30258dea0f10529ab7a63b1df03b1f9a8d638781cddc29f2903b5daf8"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "2bbbe84ce305111cb5cd483ddb75497da9fac5e29074ba527fcbb719c8f5e8f8"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "c5a294ef234b8a198822c9ec440f518fc07b403d0b9d43322bb1374010392ee5"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "6a276227babe17932a41f0c01c5f3e3aaf02e72fbf18b5e61615785419a163f8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "3426d09d09b73b67579cd680eb2ac7a9687707a3b6b84dc162b73b5166e45742"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "3e30a977c606f6d7be69e3db61fd147aa48c633fbceefa91e0223fbf493db41b"
metafile = true

[[files]]
file = "servers.dat"
hash = "fd4962951c610748761e3d1530542dd02bfd3e94cf5a5bbad74fca31e9d4359f"
