hash-format = "sha256"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "658f1fa15243f40bc82d920379ccc1e5ce5d3a039dda82a180d45d9ebf309b2e"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "b75ccc24ddb7fdd8e91f16a568885abd88b00876e9ffe40578d1cf0ce6d7371d"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/entityculling.json"
hash = "3955e3822546d7193b0432b91ba89e233a7b4aaf88cbf2883d1931c77bbc9fdb"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "20a7c9a9d1ec3c730f37af63357d6847afbb28fd37cd13657928c3d22feb055c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "1570d389b7f47caa8256fcf023243cd510d37eda62a611c8e27936c12d93d806"

[[files]]
file = "config/yosbr/config/threadtweak.json"
hash = "545cbe317c5146bacb9e13c7c03a605f0b6bd6e1ddaf1a05f8be8537d6f8b0ce"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/options.txt"
hash = "cfd15bd7cf3b9570c62f5d909136c886a3da3ca71f3dd1b2fb90d4ed21852452"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "57c157ebf3f36495fa14668c3906e70726a83564c7d0071507fc85baa106626c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "db16cd34b809cd98e78bf47cd03c8071d71b2b6c4c5e26ef5efed363207bbed2"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "df15648dd4d4e27dd0c45ab4e78277c45886b77a698b129f4ce2d2bc337f7044"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "d3a3aa18706312382e9b4e4132eac9fe26af36f272149132ec4296b79bfc0c4d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "34ef3b2634e0c8466530e488cc024ea95dfcf70d378599aa8c8b54d901bff0c5"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "6c94f2d5e791983e7cd4d7f2deb3e0abe1d8531ff42843aab1f7e4d8505a44d4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "8d27571711f951c6d5e23eed5c15c48bf7cf7347a3c03ff396ef4a2fb2baa90f"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "18e346acc11ee4082d56b804810909a69010a26eb27ac1ac3840489a6ed754fb"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "3a92166cbee839bacbfdb69ab669db430a39ed3f1891654324650e0513353724"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1ef554f7a8d5f7ed4bc21316e034eeef3430dc306012c0a706bd4c3e4ac253aa"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5b6cadef65019131a6e7d362b81bb25871330db67ef6c6b1d552e1fbd975e3be"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "2b699ec9fd674b493af0e52bc3ecbbdb3dc890a6d70f132dc146d5331c0d5b28"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "a9f27fe1325b22687f90b2fcbb94dd07e7212b3f20c1dc344f1ef16df3878bf1"
metafile = true

[[files]]
file = "mods/legacy4j.pw.toml"
hash = "e40df22e8b18a6d2e7b02480a29cafd1826ca14b0b120dd2209c5c6083ba3eeb"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "df9d69dc784ef61e99064407952d34c294f62fe1155b5260f825bd9a82e2f3a2"
metafile = true

[[files]]
file = "mods/minimega.pw.toml"
hash = "c7466c64f7619e8c04083cc850cc4368c14085d51318eede5419d39e5ecd5101"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a874985359eaa4317b3242136fe65b86207a6d5ab55e0b4aa8f37b90727f0487"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "108aae1d2a8f03fffeb5f36e874d378d521f9779cf476e4e60b7f2a8043252f6"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "4044051a3cb2ae86edab32775bbe99f2c379afde47d7fe0b1f8ff2897447a59e"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "585e3b8144192b82e4fcbc36c4b1d8355789feb034acf8dd0d7f6c46692dd39c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "09d2dbee70e91e8859e6f62e4181a80264d6dd24cc686fbedb93dda9f69fdfe6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "d3de87a755bc307790ae85f03dab53eddec2b19d906e4b5016e0e0c5004d65d0"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e9b1a059e78cb42dbc46c30f7b16d28b1bb0df20f85f53d28992ea278214a511"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "resourcepacks/legacy-skin-packs.pw.toml"
hash = "3c078794557a1ce93476771bbcf61306d82824d11621f08152396904fe8e45bc"
metafile = true

[[files]]
file = "resourcepacks/legacy-skins-pack-ordering.pw.toml"
hash = "9243fdbcadf7f6bf5a32f2b73e50ce7d374f99b685a7d1d5cf77c1ec76f60c46"
metafile = true

[[files]]
file = "resourcepacks/legacy-worlds.pw.toml"
hash = "aed5efab46de12e572df2b7f73173d7536552b941d796ca7afea7d8218c6afa1"
metafile = true

[[files]]
file = "resourcepacks/modern-skin-packs.pw.toml"
hash = "94fd733b190559644dec07baaf39956854bdd510a2854e3bbbdfab6eb92d9b5c"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "1c3e06c2051f59e8c258e93230ccaeab3894b7e3d20e46afbcde18b1216e388f"
metafile = true
