#Boost sharpness enchantment to 1.25 damage points per level instead of just 0.5.
boost_sharpness = false
#Expand all entity hitboxes by 10%, making hitting a target possible from a slightly greater range and with much increased accuracy.
inflate_hitboxes = false
#Is the sweeping edge enchantment required to perform a sweep attack.
require_sweeping_edge = true
#Attacking will no longer stop the player from sprinting. Very useful when swimming, so you can fight underwater without being stopped on every hit.
sprint_attacks = true
#Sprinting and attacking no longer interfere with each other, making critical hits possible at all times.
critical_hits_while_sprinting = true
#Completely remove the attack cooldown as if it never even existed in the first place.
remove_attack_cooldown = true
#Makes knockback stronger towards targets not on the ground (does not apply when in water).
upwards_knockback = true
#Only damage tools by 1 durability instead of 2 when attacking. Apply the same logic to swords when harvesting blocks.
no_item_durability_penalty = true
#Allow using the "Attack" button while the "Use Item" button is held for mining blocks. Does not make a lot of sense, but it used to be a feature in old pvp.
interact_while_using = false
#Give Regeneration V and Absorption I instead of Regeneration II and Absorption IV after consuming a notch apple.
notch_apple_effects = true
#Health only regenerates every 4 seconds, while requiring 18 or more food points. Surplus saturation does not yield quick health regeneration.
legacy_food_mechanics = false
#Player is knocked back by attacks which do not cause any damage, such as when hit by snowballs, eggs, and fishing rod hooks.
weak_attacks_knock_back_players = true

[adjustments]
	#Disable rendering for certain particle types from modern combat, since they kinda clutter the screen since attacks can be dealt much quicker with classic combat options enabled.
	#This option can be used to prevent basically any particle from showing.
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
	canceled_particles = ["minecraft:damage_indicator", "minecraft:sweep_attack"]
	#Prevent various attack sounds added for the cooldown mechanic from playing.
	#This option can be used to prevent basically any individual sound from playing.
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
	canceled_attack_sounds = ["minecraft:entity.player.attack.crit", "minecraft:entity.player.attack.knockback", "minecraft:entity.player.attack.nodamage", "minecraft:entity.player.attack.strong", "minecraft:entity.player.attack.weak", "minecraft:entity.player.attack.sweep"]
[attributes]
	#Overrides for setting and balancing attack damage values of items.
	#Takes precedence over any changes made by "legacy_attack_damage" option, but requires it to be enabled.
	#As with all items, this value is added ON TOP of the default attack strength of the player (which is 1.0 by default).
	#Format for every entry is "<namespace>:<path>,<amount>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
	custom_attack_damage_overrides = []
	#Revert weapon and tool attack damage to legacy values.
	legacy_attack_damage_values = true
[fishing_rods]
	#Hooking entities with a fishing rod causes only 3 damage points to the rod instead of 5.
	slower_breaking = true
	#Fishing rod deals knockback upon hitting an entity.
	cause_knockback = true
	#Entities reeled in using a fishing rod are slightly launched upwards.
	launch_entities = true
