name = "Re-Console"
author = "omo50"
version = "0.12.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc05bebc19350cebcabb00dfea62246436737ba7be8a49d168031544aa145825"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
