hash-format = "sha256"

[[files]]
file = "config/crash_assistant/config.toml"
hash = "e201fa917ffd624e255599c43a51dd0e1450b20a587d88086a7c4aa5e16ffaf9"

[[files]]
file = "config/crash_assistant/lang/README.md"
hash = "bd2631461374ee995478917064980edee09d5c300dfde1548264c1d9b6763349"

[[files]]
file = "config/crash_assistant/lang/en_us.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/ru_ru.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/lang/zh_cn.json"
hash = "3a429334ee23f897a7f9433e25af1246a735b289629d32cb0c730a9885a3c240"

[[files]]
file = "config/crash_assistant/modlist.json"
hash = "e991d9d5def8431a7a765da06eafc9c59f2911a8b39c4d483f96ff8eb0a57560"

[[files]]
file = "config/crash_assistant/problematic_mods_config.json"
hash = "ac39420512ece55a61087db09fe6c4375aa8bd02966b78716c3e3e404938f693"

[[files]]
file = "config/legacy/client_mixin.json"
hash = "ace4602e3fd17695499bd3c4c098009bd0e78d7c8e094428688d262a85236d8f"

[[files]]
file = "config/legacy/client_options.json"
hash = "72601a9c04c5e2ebadc0f7dba9abe2bcc87f5056be9beb90cf37054f33f486b0"

[[files]]
file = "config/legacy/common.json"
hash = "102803aae5342ed1907d7c1aa18b5ea41f622ab588a6b1c9694ae41f962d5b3a"

[[files]]
file = "config/legacy/common_mixin.json"
hash = "8c3090d5ad28a65c7f946726318c7b578e9708cec49fc2eee99f746780e002bf"

[[files]]
file = "config/legacy/global_packs.json"
hash = "8af063ed80c9805b95a56a125b4a6ef3899d7a08c2d882fda989436cdfd02cbd"

[[files]]
file = "config/nostalgic_tweaks/backup/nostalgic_tweaks-client-startup_backup.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/nostalgic_tweaks/nostalgic_tweaks.json"
hash = "fabdef222b32fa6712f7e594b51aaf4ff1e95db78a03b1094e00392a03714cc2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "e0d9ce47a87536c707b797789b53e9e4f09b273f69098b1303b0815ebd82b3c5"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "20bb880eb7a4657399b86fd11f6e2ec56c87c04ad037d62c155dcca5d484aa7f"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"
hash = "69b2e8613a2e3084367295c7b74cb598957f97bb9b9cfe56eb7b7a3187d86b66"

[[files]]
file = "config/yosbr/config/bettergrass.json5"
hash = "5ba4ad8c50ca8715fe648e7e68e8b5df0fe05acac0f9b152cedd93a6250ae386"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "dda5b7b8f667e02c239390c96f2a6f84d2224c7be2449e2a75a2a7fc5a96e636"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "080ec08b7754723a3fa7c45cc0c37f251cc69ff5a07c06bb0f9cb40596373bbe"

[[files]]
file = "config/yosbr/config/cpm.json"
hash = "3870f1965e60dc67b321c224c41868293c75a595c4f510b2edcff879b7372775"

[[files]]
file = "config/yosbr/config/craftpresence.json"
hash = "616adff7c23266696effd21b205000087433333b99f689ca25e65520012324b2"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"
hash = "6ef9e4a1132e7aeab97f6829893124078b95be3c9a5b247754c2ccc9deb423ce"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "4c7872ece540160831d0c17e505336ffa2fba0748f3f32f137af1958272e200c"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "4b404c16b82563e05e0cc8dc1218eb6194b2aa4473f348ff0c0c7a8655d9b5ff"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "40413b8a4f6d5495dc689ab7d812f867f7d07f3696a5a985432e93e7cda9a3db"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "22caf99f6531254b612c35bc12aff9c2b6d121b038b2e418a1a429049d16c9e0"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ee8d1a6f11ea009f37abba6325d97766910e1786b0de848aa307771d8a87ed72"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "f546f5a9367d113277de4051e3c14b898dea9490d9bd9f8240f222e0ea062c22"

[[files]]
file = "config/yosbr/config/ryoamiclights.toml"
hash = "d6afc19db2764da5ae94c735f9544987a5a4686305d1478d31fdca800a94444c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "9119e990f7bf6d27b9761144fa9a8ed9168a575f3c54d83815aedbbb3c594a49"

[[files]]
file = "config/yosbr/config/world-host.json5"
hash = "024ab81167c90c77a81797fdc769b7d4b96c2d2be076b5f94ce28c289c05cd1d"

[[files]]
file = "config/yosbr/options.txt"
hash = "74dd4f49660613476a80e9137349f512346b6bec5298e793ece0225c1d2d00ad"

[[files]]
file = "config/yosbr/resource_albums.json"
hash = "ecd81924a3b2ad635ddbeef550da86d325300a88ecd133daa70de8c3ed6c9242"

[[files]]
file = "config/yosbr/resource_albums/minecraft.json"
hash = "7927054f76453e53e697a23c64483ec11b66311681243c0a58d11602405bef5c"

[[files]]
file = "config/yosbr/resource_albums/minecraft_classic.json"
hash = "56b2d1a673da56a2a874284efb869eda80f4cbccf3012292797df0736762ed54"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "015ebf9ad50e25c5506e4ec480812104b6b2233495d256b2de4ccb16dd164d77"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "64c07d9bf7a55ddd642566876b45bb5ac78debc9e0cf8b0d05bae79aa665def6"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "5711358de644e8fbbb3fd0ccde6ea736abc0a2fe2a681a91ceee2ee759c546d8"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "883b33982262b1814b944674e61e3562c07d1028e2023ac376ac68bc86d622e0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b50378ddd8de5877ce51ded7616ebbf3ad0a5e18af8125a473411fbabc6c37cd"
metafile = true

[[files]]
file = "mods/crash-assistant.pw.toml"
hash = "d290bb6a7551ed5454d079ab99d2997669b3cbafa491ce67ce24072f35b8a9e9"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "23bdbf17e1fd8aeed7efeeea72741662734199dbef0b2adfac2ba795acf5ca40"
metafile = true

[[files]]
file = "mods/custom-player-models-fabric.pw.toml"
hash = "c78bbe75370741e3b8c1706425ca4923cbee683cb560476d00b16ebb1e1a4a78"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "8f89f3db3ee1ee8d91f28ad870dadb0a66ac3792f2bef83b0f29f413000bdc1d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4d59d6316cd914eaff7c0df2b416dc512022f9378741a88d813da82628e14b6d"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.pw.toml"
hash = "2c1d05da2179691fc1c27b53eaf942c32ff1528739a9be5e3a34dd2a92105696"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "595d4e5dbee4c4fad7a84c809491ddfa29a9607a8982d04dd19f99a3a70f1cf8"
metafile = true

[[files]]
file = "mods/entity-texture-features-fabric.pw.toml"
hash = "525d444d3184718ef1aa766f36ece7c94c7692acd0d93ca2aeed2e041089335b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "464c6feba95b2c2e31cf177c971dfae62dc1d7821d5ff7c57992a59b0b812c39"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "92c362a4e1e0bd5addf47fa90a54591acd0cc314063225b193f5f03df35753c5"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "2f7af5a78203cdef9cff4d980091afbf5ded95a9ccf24dc9cfc2989c482cfe81"
metafile = true

[[files]]
file = "mods/factory-api.pw.toml"
hash = "0350123fc2e194c828326811a4b74f48409bb268e3f3499a0aca56d4f578c750"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "1bcebf42f650151bf068b968e2b27b05c4b278bb9a31f2c0b64c4a462d3ff787"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eec16279b36b3341de41760b91675d96bb5028579dabda7c06397c5a0bf6c087"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "b31e45972ba08291e168f9d93ed14d679a8799983b7bce7ca38faa795a85bf3a"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "0a1766a1cdd5934a525dfad5350409d84df413b127ffd0433af18b87ea7efadf"
metafile = true

[[files]]
file = "mods/legacy-minecraft.pw.toml"
hash = "15cc6e56e961fa660c04a1ee92cdd34de980fc4c8cd94bbe502acac91d9b40fc"
metafile = true

[[files]]
file = "mods/legacy-skins.pw.toml"
hash = "3f6587d4bc23681e1114892046ce34bf866b175855088e903cebd6b856e398e6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3fdc92ff58a76637e11877ce3855dfee8448390e471a7597b842e744574b1c95"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "792a5f0fe941e7c9175cb7234b025c1e661a65f3d7272c1fc4cf8cea4015036e"
metafile = true

[[files]]
file = "mods/model-gap-fix.pw.toml"
hash = "1c96dae7535482219f75babe4e6e9b1ff834cf4318ecf6018fd0d5dbdd820456"
metafile = true

[[files]]
file = "mods/moderner-beta.pw.toml"
hash = "97943d9e91f5521cc4dfc4c8be213cc50ba2f5bf4f702888e70e1b56bfcbcdec"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d8eebd41737b9f1d9c106bf39ed651426c2807abe6b1f61f04eb37e4b3d68f3a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c2fe9a1900ceb3a6014ccb83344aa4ab5ddf65c8bf660044469c3c90c7ed9010"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "569e6d716ef6101e1e9957d02314101a70c9a5344828a546487b3c3a0192cc9d"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "b7c16c4d4f6df115037e9446a7f55dab37b12e1a31a88955ea4dd0d9928a5aae"
metafile = true

[[files]]
file = "mods/nostalgic-tweaks.pw.toml"
hash = "03b7066b0a4c7dce9a626d8653bdc8974b99073888b43c010550229f4ce9825a"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "02f0a9c17ee1b3a16df84cd54a8cf73636fad9ea5d8cd065a8ce5bfef6c02eb4"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "fd6eb02504e86e4c0691c6d2b4dc852a6d634ebd49cb558005435e1138251f25"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "8cb6772e366f46ca6968bfc2d91857ee6d8fbb74f0e51d96232477da5cd42f8e"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "898e14275dd5cc187dee2b8f8fc83b4f0cdb56430b7fa64a8055e006d0249ce7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/text-placeholder-api.pw.toml"
hash = "605e24df28c2facc0e22397656ff507548b86badc0a8fbc278c72f6ccd3da242"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "75598428be8e6430a4b6e64942fc79219be7add430b3fbe232f9685a18a7ba78"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "bbbcf529b4c35f04e733922ca06dde4aac8d97a556e4396da25d99e2d079c0c9"
metafile = true

[[files]]
file = "resourcepacks/re-console-resources.pw.toml"
hash = "3e30a977c606f6d7be69e3db61fd147aa48c633fbceefa91e0223fbf493db41b"
metafile = true
